Databron: https://denhaag.dataplatform.nl/#/data/1ffa4758-d143-4d78-b510-a713ab8365df

"Beschrijving: Meldingen van burgers in de openbare ruimte. De data wordt sinds januari 2024 door de betreffende afdeling niet meer geleverd. De bestanden bevatten dus historische gegevens van vóór die datum. De shape en geojson bestanden bevatten de meldingen waarvan de locatie is aangeduid met behulp van het dichtstbijzijnde adres, waarvan de coördinaten bekend zijn. Dit betreft ongeveer 80% van het totaal aantal meldingen. De meldingen gaan tot ongeveer 3 jaar terug. Het csv bestand bevat alle meldingen, ook die zonder exacte locatie aanduiding, en gaat terug tot 1 januari 2013. Hiervan is het percentage meldingen met coordinaten ongeveer 60%."

# Eerste dataverkenning

# Importeer de benodigde Python‑packages

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Laad de data en bekijk de eerste vijf rijen van de dataset

In [29]:
df = pd.read_csv('meldingen_.csv', low_memory=False)
df.head()

,WKT,ogc_fid,zaaknummer,zaaktype,niveau1,niveau2,niveau3,niveau4,stadsdeel,registrdat,...,huisletter,toevoeging,wijk,buurt,afdeling,oplossing,counter,objectid,xcoord,ycoord
0,MULTIPOINT ((76375.119 453365.016)),1,734187,Melding Openbare Ruimte,"Riolering, Water en Constructies",Riool,huisaansluiting,kan niet lozen,Loosduinen,2016-07-01T12:28:35,...,NaN,NaN,Waldeck,Nieuw Waldeck,Riolering,Opgelost,186,186,76375.119,453365.016
1,MULTIPOINT ((85510.15 451385.08)),2,734191,Melding Openbare Ruimte,Afval,Verzamelcontainer,Restafval,Vol,Leidschenveen-Ypenburg,2016-07-01T12:34:42,...,NaN,NaN,Ypenburg,Morgenweide,HMS,NaN,189,189,85510.150,451385.080
2,MULTIPOINT ((76401.81 452015.138)),3,734194,Melding Openbare Ruimte,Afval,Zwerfvuil,Op openbare weg,NaN,Loosduinen,2016-07-01T12:39:57,...,NaN,NaN,Loosduinen,Houtwijk,Straten-serviceploeg,Wordt meegenomen in gepland onderhoud,191,191,76401.810,452015.138
3,MULTIPOINT ((78874.023 456134.274)),4,734195,Melding Openbare Ruimte,Afval,Inzameling huisvuil,Huisvuilzak,Niet opgehaald,Scheveningen,2016-07-01T12:40:00,...,A,NaN,Geuzen- en Statenkwartier,Statenkwartier,HMS,NaN,193,193,78874.025,456134.278
4,MULTIPOINT ((80003.281 455564.21)),5,734196,Melding Openbare Ruimte,Straten en straatmeubilair,Anti-parkeerpaal/ Hagenaartje,Verwijderen,NaN,Centrum,2016-07-01T12:40:02,...,NaN,NaN,Zeeheldenkwartier,Zeeheldenkwartier,Wegbeheer Centrum,Informatie verstrekt,195,195,80003.281,455564.210

Laten we de kolomnamen bekijken

In [31]:
df.columns

Index(['WKT', 'ogc_fid', 'zaaknummer', 'zaaktype', 'niveau1', 'niveau2',
       'niveau3', 'niveau4', 'stadsdeel', 'registrdat', 'verlengen',
       'vervaldat', 'afgerondop', 'binnenkmst', 'prioriteit', 'externstat',
       'internstat', 'straat', 'huisnummer', 'huisletter', 'toevoeging',
       'wijk', 'buurt', 'afdeling', 'oplossing', 'counter', 'objectid',
       'xcoord', 'ycoord'],
      dtype='object')

Laten we het aantal meldingen bekijken

In [30]:
len(df)

468553

We zien in totaal 468.553 meldingen. Laten we kijken van welk jaar tot welk jaar deze meldingen lopen.

In [32]:
df['registrdat'].value_counts().sort_index()

registrdat
2016-07-01T01:26:58    1
2016-07-01T07:25:51    1
2016-07-01T07:45:21    1
2016-07-01T08:04:30    1
2016-07-01T08:06:03    1
                      ..
2024-01-15T11:38:25    1
2024-01-16T18:37:47    1
2024-01-17T15:55:33    1
2024-01-18T12:22:00    1
2024-01-18T16:09:00    1
Name: count, Length: 467376, dtype: int64

We zien dat de registraties lopen van 2016 tot en met 2024. Laten we een nieuwe kolom aanmaken zodat we de data per jaar kunnen bekijken en groeperen.

In [62]:
print(df.dtypes)

WKT            object
ogc_fid         int64
zaaknummer      int64
zaaktype       object
niveau1        object
niveau2        object
niveau3        object
niveau4        object
stadsdeel      object
registrdat     object
verlengen      object
vervaldat      object
afgerondop     object
binnenkmst     object
prioriteit     object
externstat     object
internstat     object
straat         object
huisnummer      int64
huisletter     object
toevoeging     object
wijk           object
buurt          object
afdeling       object
oplossing      object
counter         int64
objectid        int64
xcoord        float64
ycoord        float64
dtype: object

In [63]:
df["registrdat"] = pd.to_datetime(df["registrdat"])

# Now check the dtype
print(df["registrdat"].dtype)

datetime64[ns]

In [126]:
df["jaar"] = df["registrdat"].dt.year
df["jaar"].head()

0    2016
1    2016
2    2016
3    2016
4    2016
Name: jaar, dtype: int32

_______________________________

# Hoeveel meldingen zijn er per jaar geregistreerd?

In [128]:
counts_per_year = df.groupby("jaar").size().rename_axis('jaar').reset_index(name='het aantal meldingen')
print(counts_per_year)

   jaar  het aantal meldingen
0  2016                 20451
1  2017                 46715
2  2018                 64062
3  2019                 72814
4  2020                 92810
5  2021                 88304
6  2022                 42417
7  2023                 40930
8  2024                    50

**Interactieve figuur**

In [129]:
fig = px.bar(
counts_per_year,
    x="jaar",
    y="het aantal meldingen",
    title="Welk jaar heeft het hoogste aantal meldingen?", color = 'jaar',
    hover_data=counts_per_year.columns  
)

fig.show()

2020 en 2021 waren de jaren met de hoogste aantal meldingen

# Hoe zijn de meldingen ingediend?

In [130]:
df['binnenkmst'].value_counts().rename_axis('manier').reset_index(name='het aantal meldingen')

                    manier  het aantal meldingen
0    formulier met geo-inf                258596
1              BuitenBeter                 99694
2                 Telefoon                 79122
3            Web formulier                 12903
4                   E-mail                  5788
5          Interne Melding                  4804
6             Social Media                  4016
7              App melding                  1273
8     Andere meldingen app                  1160
9          Verbeterdebuurt                  1076
10                   Balie                    48
11                   Brief                    40
12        E-mail Ombudsman                    18
13            Fietsersbond                     8
14        Mobiel formulier                     5
15   Brief (regio/6 weken)                     1
16  Post (buiten regio HL)                     1

In [131]:

counts = (
    df.groupby(["jaar", "binnenkmst"])
    .size()
    .rename("het aantal meldingen")
    .reset_index(name='het aantal meldingen')
)



counts_sorted = counts.sort_values("het aantal meldingen", ascending=False)

counts_sorted.head(10)

    jaar             binnenkmst  het aantal meldingen
72  2020  formulier met geo-inf                 50680
84  2021  formulier met geo-inf                 45678
98  2023  formulier met geo-inf                 40553
95  2022  formulier met geo-inf                 36324
58  2019  formulier met geo-inf                 34985
44  2018  formulier met geo-inf                 30062
76  2021            BuitenBeter                 26063
63  2020            BuitenBeter                 21968
49  2019            BuitenBeter                 19433
26  2017               Telefoon                 16616

In [133]:
fig = px.bar(
    counts,
    x="jaar",
    y="het aantal meldingen",
    color="binnenkmst",
    title="Aantal meldingen per manier van binnenkomst per jaar",
    barmode="group"
)

fig.show()

Het formulier met geo‑informatie was de meest gebruikte manier van meldingen indienen. In 2023 bleken meldingen alleen via het formulier met geo‑informatie en het webformulier te zijn ingediend.

Wat is er aan de hand?

In [138]:
counts_per_year_per_issue = (
    df.groupby(["jaar", "niveau1"])
    .size()
    .rename_axis(["jaar", "kwesties"])
    .reset_index(name="het aantal meldingen")
)

print(counts_per_year_per_issue)

    jaar                                    kwesties  het aantal meldingen
0   2016                                       Afval                 11469
1   2016                      Bedrijven/ evenementen                    66
2   2016     Graffiti/ posters/ stickers verwijderen                   207
3   2016                                       Groen                  1444
4   2016                  Onveilige verkeerssituatie                   219
..   ...                                         ...                   ...
95  2024                                    Parkeren                     4
96  2024            Riolering, Water en Constructies                    19
97  2024                                Speelterrein                     1
98  2024                  Straten en straatmeubilair                     5
99  2024  Verkeerslichten/ borden/ straatverlichting                    14

[100 rows x 3 columns]

In [140]:
fig = px.bar(
  counts_per_year_per_issue,
    x="jaar",
    y="het aantal meldingen",
    color="kwesties",
    title="Aantal meldingen per kwestie per jaar",
    barmode="group"
)

fig.show()

De meeste meldingen blijken afval‑gerelateerd te zijn.

# Oplossingstatus

In [141]:
df['oplossing'].value_counts().rename_axis('status').reset_index(name='het aantal meldingen')

                                          status  het aantal meldingen
0               Handhavingsorganisatie oplossing                 82619
1          Wordt meegenomen in gepland onderhoud                 63380
2                           Informatie verstrekt                 56670
3                                       Opgelost                 51624
4          Wordt verder behandeld in GISIB (OVL)                 22973
5                                      Afgewezen                  8611
6            Wordt verder behandeld in HPS (R&W)                  4773
7        Wordt verder behandeld in Viadesk (R&W)                  3953
8           Wordt verder behandeld in Vera+ (VM)                  1507
9           Wordt verder behandeld in OVIN (OVL)                   727
10                          Straten-serviceploeg                   359
11  Wordt verder behandeld in BWT4All (Graffiti)                   131
12          Wordt verder behandeld in MPM (MenV)                   123

In [142]:

counts_oplossing = (
    df.groupby(["jaar", "oplossing"])
    .size()
    .rename("het aantal meldingen")
    .reset_index(name='het aantal meldingen')
)



counts_sorted_oplossing = counts_oplossing.sort_values("het aantal meldingen", ascending=False)

counts_sorted_oplossing.head(10)

    jaar                              oplossing  het aantal meldingen
48  2020       Handhavingsorganisatie oplossing                 15538
60  2021       Handhavingsorganisatie oplossing                 14820
36  2019       Handhavingsorganisatie oplossing                 12670
88  2023  Wordt meegenomen in gepland onderhoud                 11654
76  2022  Wordt meegenomen in gepland onderhoud                 11609
24  2018       Handhavingsorganisatie oplossing                 11466
50  2020                               Opgelost                 10071
38  2019                               Opgelost                  9906
13  2017       Handhavingsorganisatie oplossing                  9784
49  2020                   Informatie verstrekt                  9522

In [143]:
fig = px.bar(
    counts_sorted_oplossing,
    x="jaar",
    y="het aantal meldingen",
    color="oplossing",
    title="Oplossingstatus per jaar",
    barmode="group"
)

fig.show()

De oplossing wordt in de meeste gevallen door de handhavingsorganisatie verleend.

# Welk stadsdeel heeft het hoogste aantal meldingen? Interactieve figuur:

In [144]:
df['stadsdeel'].value_counts().rename_axis('stads_deel').reset_index(name='het aantal meldingen')

               stads_deel  het aantal meldingen
0                  Escamp                 99316
1                 Centrum                 91480
2                Segbroek                 57405
3            Scheveningen                 53477
4              Loosduinen                 47535
5                    Laak                 38391
6             Haagse Hout                 37933
7  Leidschenveen-Ypenburg                 36547

In [150]:
stads_deel = df['stadsdeel'].value_counts().rename_axis('stads_deel').reset_index(name='het aantal meldingen')

In [151]:
stads_deel_hoge_meldingen = stads_deel.iloc[:5].copy()

In [153]:
fig = px.bar(
    stads_deel_hoge_meldingen,
    x="stads_deel",
    y="het aantal meldingen",
    title="Welk stadsdeel heeft het hoogste aantal meldingen?",color="stads_deel",                              
    color_discrete_sequence=["red", "orange", "yellow", "grey", "purple"],
    hover_data=stads_deel_hoge_meldingen.columns  
)

In [154]:
fig.show()

per jaar:

In [156]:

counts_deel = (
    df.groupby(["jaar", "stadsdeel"])
    .size()
    .rename("het aantal meldingen")
    .reset_index(name='het aantal meldingen')
)



counts_sorted_deel = counts_deel.sort_values("het aantal meldingen", ascending=False)

counts_sorted_deel.head(10)

    jaar stadsdeel  het aantal meldingen
33  2020    Escamp                 20497
41  2021    Escamp                 18761
40  2021   Centrum                 17211
32  2020   Centrum                 17017
25  2019    Escamp                 15330
24  2019   Centrum                 14048
17  2018    Escamp                 13691
16  2018   Centrum                 12909
47  2021  Segbroek                 11614
39  2020  Segbroek                 11286

In [157]:
counts_sorted_deel["stadsdeel"].value_counts()

stadsdeel
Escamp                    9
Centrum                   9
Segbroek                  9
Scheveningen              9
Loosduinen                9
Laak                      9
Haagse Hout               9
Leidschenveen-Ypenburg    9
Name: count, dtype: int64

In [158]:
fig = px.bar(
    counts_deel,
    x="jaar",
    y="het aantal meldingen",
    color="stadsdeel",
    title="Welk stadsdeel heeft het hoogste aantal meldingen?",  barmode="group",                          
 
    hover_data=counts_deel.columns  
)

fig.show()

Escamp en Centrum lijken de stadsdelen met de hoogste aantal meldingen te zijn.

# Bubble map:

In [159]:
df_clean = df.dropna(subset=["stadsdeel"])
counts_deel = (
    df_clean
    .groupby(["jaar", "stadsdeel"])
    .size()
    .rename("het aantal meldingen")
    .reset_index(name='het aantal meldingen')
)

In [162]:
stadsdeel_coords = pd.DataFrame({
    "stadsdeel": [
        "Centrum",
        "Escamp",
        "Segbroek",
        "Scheveningen",
        "Loosduinen",
        "Laak",
        "Haagse Hout",
        "Leidschenveen-Ypenburg"
    ],
    "lat": [
        52.0707,
        52.0609,
        52.0450,
        52.0900,
        52.0400,
        52.0650,
        52.0500,
        52.0900
    ],
    "lon": [
        4.3126,
        4.3600,
        4.3300,
        4.2100,
        4.2700,
        4.3250,
        4.3400,
        4.3800
    ]
})

counts_geo = counts_deel.merge(stadsdeel_coords, on="stadsdeel", how="inner")

if counts_geo.empty:
    print("ERROR: counts_geo is empty → check stadsdeel names match exactly!")
    print("stadsdeel unique in counts_deel:")
    print(counts_deel["stadsdeel"].unique())
else:
   
    fig = px.scatter_mapbox(
        counts_geo,
        lat="lat",
        lon="lon",
        size="het aantal meldingen",
        color="het aantal meldingen",
        color_continuous_scale="Blues",
        hover_name="stadsdeel",
        hover_data=["het aantal meldingen", "jaar"],
        zoom=9,
        mapbox_style="open-street-map",
        title="Aantal meldingen per stadsdeel (Den Haag)"
    )

    fig.update_layout(
        margin={"r":0, "t":40, "l":0, "b":0},
        coloraxis_colorbar=dict(title="Aantal meldingen"),
        width=900, height=600
    )

    fig.show()